# Generated by Django 5.2.7 on 2025-10-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='your_colleagues_for_the_project',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='your_project_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
