##### Review

The following formula computes a _Z score_ and measures how far a single raw data value is from the population mean.

\begin{equation*}
z = \frac{X - \mu }{\sigma }
\end{equation*}

where:
* **_X_** is a single raw data value
* `mu` is the population mean
* `sigma` is the population standard deviation

To find the standard deviation, the equation below comes in hand:

\begin{equation*}
\sigma = \sqrt{\frac{\sum \left | X - \mu \right |^{2}}{N}}
\end{equation*}

where **_N_** is the number of data points in the population.

**a.** Using `sum()` and `list comprehension`, compute the mean and the standard deviation for the population defined below:

In [1]:
data =  [4.5, 5, 5.5, 6, 6.25, 7, 15.25, 18, 18.45, 21, 21.45, 23]
print(data)

[4.5, 5, 5.5, 6, 6.25, 7, 15.25, 18, 18.45, 21, 21.45, 23]


In [2]:
# Your implementation here:
mean = sum(data)/len(data)
std = (sum((x-mean)**2 for x in data)/len(data))**0.5

print (mean, std)

12.616666666666667 7.167441818544622


**b.** Define the `z_score()` function and implement the mathematical expression. The obtained values should be stored in a _z score_ values list and rounded to 3 decimals.

In [3]:
# Your implementatio here:
def z_score(X, mean, sdt):
    if sdt == 0:
        return "Cannot divide by 0"
    return (X - mean) / sdt

**c.** Add the corresponding elongation of each raw data value into a dictionary.

In [4]:
# Your implementatio here:
results = [round(z_score(X, mean, std), 3) for X in data]
e = {data[i]: results[i] for i in range(len(data))}

print (e)

{4.5: -1.132, 5: -1.063, 5.5: -0.993, 6: -0.923, 6.25: -0.888, 7: -0.784, 15.25: 0.367, 18: 0.751, 18.45: 0.814, 21: 1.17, 21.45: 1.232, 23: 1.449}


## Classes

The object-oriented programming paradigm in Python helps with structuring programs into `individual objects`. But how?

* An Object **O** from a class **C** has a set of properties **_p_** and actions **_a_**.

* The functions of a class are called `methods`. Their responsibility is to model the data corresponding to a given object.

* The objects of a class are known as `instances` and represent the source of collecting data.

```python

class EmptyClas:
    """
    This is a class without variables and methods
    """
    pass # The keyword pass is a placeholder


class MyClass:
    # A class variable
    name = 'My Class'
    
    def my_method(self, my_var):
        # An instance variable
        self.my_instance = my_var
```

In [5]:
# Implement Task 0 b and c here:

class ScientificConference:
    r"""
    To define the properties of a class, 
    we use a special method called __init__.
    
    The special variable called "self"
    helps with associating the attributes
    w\ the new object: similar to `this`
    keyword from other programming languages
    and required to address variables from
    classes. 
    """
    def __init__(self, name, year, papers=None):
        """
        Establish the attributes of the
        class and assign values to the 
        corresponding parameters.
        """ 
        self.name = name
        self.year = year
        """
        b. Add new attribute `papers`
        """
        self.papers = papers if papers is not None else {}

    
    def add_manuscript(self, title, researcher):
        if researcher not in self.papers:
            self.papers[researcher] = []

        if title in self.papers[researcher]:
            return

        self.papers[researcher].append(title)        

    def __str__(self):
        """
        To return the String representation of
        an object, we use the __str__ method. 
        """
        result = self.name + ' ' + str(self.year) + ': \n'
        for author, papers in self.papers.items():
            result += f'{author}: {", ".join([str(paper) for paper in papers])} \n'
        return result

### Task 0

**a.** Define two new `instances` of the `class ScientificConference` and return their representations.

Your output should look like:

`Proposals for ICML and NeurIPS conferences will be accepted until the end of November 2021.`

_Hint:_ `instance.attribute` helps you extracting a certain property.

In [6]:
# Your implementation here
icml = ScientificConference("ICML", 2021)
neurips = ScientificConference("NeurIPS", 2021)
f"Proposals for {icml.name} and {neurips.name} conferences will be accepted until the end of November {icml.year}."


'Proposals for ICML and NeurIPS conferences will be accepted until the end of November 2021.'

**b.** Create a new attribute for the `class ScientificConference`, which is a dictionary passed as a parameter to the instances of the class and holds all of the papers of the conference.

_Note:_ You should check if `papers` is `None` in `__init__` and set it to `{}` instead.

_Please handle duplicate entries by removing them!_

**c.** Define the `add_manuscript` method which generates new entries in the dictionary described before. Please consider using the _researcher_ as a `key` and the _title_ as `values`.

In [7]:
conf = ScientificConference("ICML", 2021, {})

conf.add_manuscript("Paper 1", "Person 1")
conf.add_manuscript("Paper 2", "Person 2")
conf.add_manuscript("Paper 1", "Person 1")  #duplicate

print(conf)

ICML 2021: 
Person 1: Paper 1 
Person 2: Paper 2 



### Task 1

**a.** Define the class `Person` which stores the `title`, `name` and `surname` of a person.

The _tuple_ `allowed_titles` is a class variable which helps to verify if the title of a person is "Mr", "Mrs", "Ms", "Senior Researcher", "Professor of CS" or "Computer Scientist".

An error is returned if the title is not valid.

Use `__str__` defined below:

```python
    def __str__(self):
        return self.title + ' ' + self.surname + ' ' + self.name
```

In [8]:
# Your implementation here
class Person:
    allowed_titles = ("Mr", "Mrs", "Ms", "Senior Researcher", "Professor of CS", "Computer Scientist")

    def __init__(self, title, name, surname):
        if title not in Person.allowed_titles:
            raise ValueError("The title isn't right")
        self.title = title
        self.name = name
        self.surname = surname
        
    def __str__(self):
            return self.title + ' ' + self.surname + ' ' + self.name

**b.** Create two instances of the class Person and verify if the following entries are valid:

* _Mr Ian Goodfellow_,
* _SeniorResearcher Tomas Mikolov._

In [9]:
# Your implementation here

p1 = Person("Mr","Ian","Goodfellow")
p2 = Person("SeniorResearcher","Tomas","Mikolov")

print(p1)
print(p2)

ValueError: The title isn't right

### Task 2

In `ScientificConference` we have been using the paper parameter as a string, but this concept requires a detailed structure.

Introduce a new class, `Paper`, which has the following attributes:

* `authors`, 
* `title`, 
* `a_id`,
* `year`, 
* `status` (published or in development), 
* `peer_rating` (Excellent, Good, Fair, Poor, Barely Acceptable, Unacceptable).

In [ ]:
class Paper:
    def __init__(self, authors, title, a_id, status, year, peer_rating):
        self.authors = authors
        self.title = title
        self.a_id = str(a_id)
        self.status = status  
        self.year = int(year)
        self.peer_rating = peer_rating 

    def __str__(self):
        return  f'{self.title}, {", ".join([author for author in self.authors])} et al. ({self.year}), a_id: '\
                f'{self.a_id}, status: {self.status}, rating: {self.peer_rating}'

## Inheritence

In Object-Oriented programming, this concept enables us to transfer the methods and the properties of a class to another class.

### Task 3

Create a class named `Researcher`, which inherits the properties and methods from the `Person` class. Besides, this class has an additional parameter, `papers` which is `None` by default.

_Note:_ You should check if `papers` is `None` in `__init__` and set it to `[]` instead.

```python
class Researcher(Person):
    def __init__('Add arguments'):
        super().__init__(title, name, surname)
```

In [ ]:
# Define your first researcher
# Expected output: Senior Researcher Tomas Mikolov

class Researcher(Person):
    def __init__(self, title, name, surname, papers = None):
        super().__init__(title, name, surname)
        self.papers = papers if papers is not None else []
        self.co_authored = False

    def add_paper(self, paper):
        self.papers.append(paper)

    def verify_co_authorship(self):
        self.co_authored = any(len(p.authors) > 1 for p in self.papers)
        return self.co_authored

    def get_collab(self, other):
        collab_papers = []
        for paper in self.papers:
            for author in paper.authors:
                if other.surname in author:
                    collab_papers.append(paper)
        return collab_papers

    def print_papers(paper_list):
        for paper in paper_list:
            print(paper)


mikolov = Researcher("Senior Researcher", "Tomas", "Mikolov")
print(mikolov)


Senior Researcher Mikolov Tomas


### Task 4

Consider the following scientists:

1.  Paper _Deep Learning_ published by Yann LeCun, Yoshua Bengio, Geoffrey Hinton, in _nature 521_, id = https://doi.org/10.1038/nature14539, peer_rating = Excelent.

2. Paper _On the difficulty of training recurrent neural networks_ by Razvan Pascanu, Tomas Mikolov, Professor of computer science Yoshua Bengio, in ICML 2013, id = https://arxiv.org/abs/1211.5063, peer_rating = Excelent.

2. Paper _Generative Adversarial Nets_ by Ian Goodfellow and Yoshua Bengio, NeurIPS 2015, id = http://papers.nips.cc/paper/5423-generative-adversarial-nets.pdf, peer_rating = Excelent.

3. Paper _Handwritten Digit Recognition with a Back-Propagation Network_ by Computer Scientist Yann LeCun, NeurIPS 1989, id =  https://papers.nips.cc/paper/293-handwritten-digit-recognition-with-a-back-propagation-network, peer_rating = Excelent.

4. Paper _Gated Softmax Classification_ by Geoffrey Hintorn, NeurIPS 2010, id = http://papers.neurips.cc/paper/3895-gated-softmax-classification, peer_rating = Good.

_Note:_ Let us consider "Mr" as a default title for the researchers without a specific caption. Also, for the id of a paper, please use only integers from the provided links.

**a.** Define the next 5 scientists and use them in your `paper` objects.

**b.** Create the `verify_co_authorship` function inside the `class Researcher` which checks if a certain researcher ever co-authored a paper.
_Hint:_ Use `self.co_authored = False` inside the `__init__` function.

**c.** Implement the `get_collab` function inside the `class Researcher` to discover the papers written by two researchers.

For instance, if Yoshua Bengio is researcher2 and Ian Goodfellow is researcher3, then:

`print_papers(researcher2.get_collab(researcher3))` should output:

_Generative Adversarial Nets, Mr Ian Goodfellow et al. (2015), a_id: 5423, status: published, rating: Excelent_

_Note:_ This function helps you to print the papers from a given list.

```python
def print_papers(paper_list):
    for paper in paper_list:
        print(paper)
```

**d.** What are the papers written by Yoshua Bengio?

Expected output:

`Deep Learning, Computer Scientist Yann LeCun et al. (2015), a_id: 14539, status: published, rating: Excelent`

`Generative Adversarial Nets, Mr Ian Goodfellow et al. (2015), a_id: 5423, status: published, rating: Excelent`

`Paper On the difficulty of training recurrent neural networks, Mr Razvan Pascanu et al. (2013), a_id: 5063, status: published, rating: Excelent`

**e.** Did he ever co-author a paper?

**f.** Which papers are published by Yann LeCun?

Expected output:

`Deep Learning, Computer Scientist Yann LeCun et al. (2015), a_id: 14539, status: published, rating: Excelent`

`Handwritten Digit Recognition with a Back-Propagation Network, Computer Scientist Yann LeCun et al. (1989), a_id: 293, status: published, rating: Good`

In [ ]:
def print_papers(paper_list):
    for paper in paper_list:
        print(paper)

lecun = Researcher("Computer Scientist", "Yann", "LeCun")
bengio = Researcher("Professor of CS", "Yoshua", "Bengio")
hinton = Researcher("Professor of CS", "Geoffrey", "Hinton")
goodfellow = Researcher("Mr", "Ian", "Goodfellow")
pascanu = Researcher("Mr", "Razvan", "Pascanu")

deep_learning = Paper(
    authors=[str(lecun), str(bengio), str(hinton)],
    title="Deep Learning",
    a_id=14539,
    status="published",
    year=2015,
    peer_rating="Excelent"
)

difficulty = Paper(
    authors=[str(pascanu), str(mikolov), str(bengio)],
    title="On the difficulty of training recurrent neural networks",
    a_id=5063,
    status="published",
    year=2013,
    peer_rating="Excelent"
)

generative = Paper(
    authors=[str(goodfellow), str(bengio)],
    title="Generative Adversarial Nets",
    a_id=5423,
    status="published",
    year=2015,
    peer_rating="Excelent"
)

handwritten = Paper(
    authors=[str(lecun)],
    title="Handwritten Digit Recognition with a Back-Propagation Network",
    a_id=293,
    status="published",
    year=1989,
    peer_rating="Good"
)

gated_softmax = Paper(
    authors=[str(hinton)],
    title="Gated Softmax Classification",
    a_id=3895,
    status="published",
    year=2010,
    peer_rating="Good"
)

all_papers = [deep_learning, difficulty, generative, handwritten, gated_softmax]
all_researchers = [lecun, bengio, hinton, goodfellow, pascanu, mikolov]

for paper in all_papers:
    for r in all_researchers:
        for author in paper.authors:
            if r.surname in author:
                r.add_paper(paper)
                break

print_papers(bengio.get_collab(goodfellow)) #c
print_papers(bengio.papers) #d
print(bengio.verify_co_authorship()) #e
print_papers(lecun.papers) #f

Generative Adversarial Nets, Mr Goodfellow Ian, Professor of CS Bengio Yoshua et al. (2015), a_id: 5423, status: published, rating: Excelent
Deep Learning, Computer Scientist LeCun Yann, Professor of CS Bengio Yoshua, Professor of CS Hinton Geoffrey et al. (2015), a_id: 14539, status: published, rating: Excelent
On the difficulty of training recurrent neural networks, Mr Pascanu Razvan, Senior Researcher Mikolov Tomas, Professor of CS Bengio Yoshua et al. (2013), a_id: 5063, status: published, rating: Excelent
Generative Adversarial Nets, Mr Goodfellow Ian, Professor of CS Bengio Yoshua et al. (2015), a_id: 5423, status: published, rating: Excelent
True
Deep Learning, Computer Scientist LeCun Yann, Professor of CS Bengio Yoshua, Professor of CS Hinton Geoffrey et al. (2015), a_id: 14539, status: published, rating: Excelent
Handwritten Digit Recognition with a Back-Propagation Network, Computer Scientist LeCun Yann et al. (1989), a_id: 293, status: published, rating: Good


### Task 5 

Consider an updated version of the `ScientificConference` class, which should have a modified version of the function `add_manuscript`.

Use the `status` and the `peer_rating` variables as a **threshold** to add papers in your `papers` dictionary. The conferences will only be accepting `Excelent` papers. For this case, the dictionary has the year of the paper as `key`, and the `values` are stored as a tuple of `(researcher, manuscript)`. For the papers which don't satisfy this condition, the message _"Please review your submission."_ is displayed.

For papers submitted in 2015, when printing the conference, the `str` function should output:

```
NeurIPS 2020: 
2015: 
Mr Ian Goodfellow: Generative Adversarial Nets, Mr Ian Goodfellow et al. (2015), id: 5423, status: published, rating: Excelent 
Computer Scientist Yann LeCun: Deep Learning, Computer Scientist Yann LeCun et al. (2015), id: 14539, status: published, rating: Excelent
```

In [ ]:
neurips20 = ScientificConferenceUpdate("NeurIPS", 2020)
neurips20.add_manuscript(generative, goodfellow)
neurips20.add_manuscript(deep_learning, lecun)
print(neurips20)

NeurIPS 2020: 
2015: 
Mr Goodfellow Ian: Generative Adversarial Nets, Mr Goodfellow Ian, Professor of CS Bengio Yoshua et al. (2015), a_id: 5423, status: published, rating: Excelent 
Computer Scientist LeCun Yann: Deep Learning, Computer Scientist LeCun Yann, Professor of CS Bengio Yoshua, Professor of CS Hinton Geoffrey et al. (2015), a_id: 14539, status: published, rating: Excelent 

